import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SessionProvider } from './context/client-provider'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={inter.className}>
          <Link href="/">Home</Link>
          {children}</body>
      </SessionProvider>
    </html>
  )
}
